name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7.0"
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-Onboarding-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-Onboarding
      - name: Build
        run: xcodebuild build -project OnboardingExample.xcodeproj -scheme OnboardingExample-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14"

